import { FORMSPREE_BASE_URL, WEATHER_API_BASE_URL } from './baseUrls'
import { FORMSPREE_API_KEY, WEATHER_API_KEY } from './apiKeys'

export const FORMSPREE_URL = FORMSPREE_BASE_URL + FORMSPREE_API_KEY
export const WEATHER_API_URL = WEATHER_API_BASE_URL + WEATHER_API_KEY
